package com.roadside.sensing

import android.util.Log

/**
 * Translates raw YAMNet AudioSet class scores into a RoadSide [AudioClassificationResult].
 *
 * SAFETY CONTRACT:
 *   - YAMNet is a general sound-event classifier, NOT a motorcycle fault detector.
 *     It has no class for chain wear, sprocket damage or pad glazing, and no training
 *     signal separating a healthy component from a worn one.
 *   - This translator produces an **evidence signal** only: "what kind of sound is this".
 *   - It never asserts a mechanical fault. Fault reasoning belongs to
 *     [com.roadside.rules.DiagnosisRules].
 *
 * INDEX PROVENANCE:
 *   Every index below was generated by resolving a label name against the shipped
 *   `yamnet_class_map.csv` (521 classes, valid range 0..520) — not hand-typed and not
 *   carried over from the previous mapping, which was almost entirely wrong (it pointed
 *   "brake" at Spray/Pump/Stir, "electrical" at four music genres, and 12 of 31 indices
 *   were out of range and silently contributed zero).
 *   If the class map is ever swapped, re-derive these from the CSV.
 *
 * AGGREGATION:
 *   Groups aggregate by **max**, not sum. YAMNet is multi-label (independent sigmoids),
 *   so summing member probabilities is not a calibrated confidence and makes a group with
 *   more members easier to trigger purely because it has more members. The max of a group
 *   is the strongest single observation supporting that group, which is comparable across
 *   groups of different sizes.
 *
 * THRESHOLDS:
 *   Every threshold below is PROVISIONAL. They are placeholders chosen to keep the
 *   pipeline runnable, NOT tuned values. Tune them only against real N160 recordings:
 *     real recording -> raw YAMNet output -> observed behaviour -> threshold change.
 */
object EvidenceTranslator {

    private const val TAG = "EvidenceTranslator"

    // ── PROVISIONAL thresholds — do not treat as tuned ───────────────────────────
    /** Vehicle/engine must reach this for "a vehicle is present" context. */
    private const val T_PRESENCE = 0.20f
    /** High-frequency friction (brake-like) evidence. */
    private const val T_FRICTION = 0.20f
    /** Buzz/hum/relay evidence. */
    private const val T_ELECTRICAL = 0.20f
    /** Rattle-family evidence. Deliberately stricter than the others. */
    private const val T_CHAIN = 0.25f
    /** General mechanical evidence. */
    private const val T_MECHANICAL = 0.20f
    /** Ambient/background evidence. */
    private const val T_AMBIENT = 0.15f

    // ── RoadSide evidence labels ─────────────────────────────────────────────────
    private const val LABEL_CHAIN_NOISE       = AudioClassificationResult.POSSIBLE_CHAIN_NOISE
    private const val LABEL_BRAKE_SQUEAL      = AudioClassificationResult.BRAKE_SQUEAL
    private const val LABEL_ENGINE_NOISE      = AudioClassificationResult.ENGINE_NOISE
    private const val LABEL_CLICKING_ELEC     = AudioClassificationResult.CLICKING_ELECTRICAL
    private const val LABEL_MECHANICAL_NOISE  = AudioClassificationResult.MECHANICAL_NOISE
    private const val LABEL_AMBIENT_ONLY      = AudioClassificationResult.AMBIENT_ONLY
    private const val LABEL_UNKNOWN           = AudioClassificationResult.UNKNOWN

    // ── AudioSet index groups (verified against yamnet_class_map.csv) ─────────────

    /** Vehicle identity — says "a vehicle is audible", says nothing about its health. */
    private val VEHICLE_INDICES = intArrayOf(
        294, // Vehicle
        300, // Motor vehicle (road)
        301, // Car
        320, // Motorcycle
        321  // Traffic noise, roadway noise
    )

    /** Engine/power-plant sounds — a NORMAL running engine lands here. */
    private val ENGINE_INDICES = intArrayOf(
        337, // Engine
        338, // Light engine (high frequency)
        342, // Medium engine (mid frequency)
        343, // Heavy engine (low frequency)
        344, // Engine knocking
        345, // Engine starting
        346, // Idling
        347  // Accelerating, revving, vroom
    )

    /** High-frequency friction — the closest AudioSet has to brake squeal. */
    private val FRICTION_INDICES = intArrayOf(
        306, // Skidding
        307, // Tire squeal
        327, // Train wheels squealing
        355, // Squeak
        479  // Squeal
    )

    /**
     * Rattle-family: impulsive/cyclic mechanical sounds.
     *
     * This is the ONLY group allowed to support chain evidence. It deliberately excludes
     * every engine class — a running engine must never, on its own, look like a chain.
     */
    private val RATTLE_INDICES = intArrayOf(
        130, // Rattle
        398, // Mechanisms
        403, // Gears
        483, // Clatter
        486  // Clickety-clack
    )

    /** Broader mechanical evidence (rattle family plus non-cyclic mechanical sounds). */
    private val MECHANICAL_INDICES = intArrayOf(
        130, // Rattle
        398, // Mechanisms
        401, // Tick
        402, // Tick-tock
        403, // Gears
        469, // Scrape
        482, // Whir
        483, // Clatter
        485, // Clicking
        486  // Clickety-clack
    )

    /** Electrical/relay sounds — solenoid clicking on a flat battery, etc. */
    private val ELECTRICAL_INDICES = intArrayOf(
        125, // Buzz
        392, // Buzzer
        485, // Clicking
        490, // Hum
        509, // Static
        510  // Mains hum
    )

    /** Background/environment — the false-positive control path. */
    private val AMBIENT_INDICES = intArrayOf(
        277, // Wind
        279, // Wind noise (microphone)
        494, // Silence
        500, // Inside, small room
        501, // Inside, large room or hall
        502, // Inside, public space
        503, // Outside, urban or manmade
        504, // Outside, rural or natural
        507, // Noise
        508, // Environmental noise
        514, // White noise
        515  // Pink noise
    )

    /** People and music nearby — background, never mechanical evidence. */
    private val HUMAN_MUSIC_INDICES = intArrayOf(
        0,   // Speech
        65,  // Hubbub, speech noise, speech babble
        132  // Music
    )

    /** Display names for the indices this translator reasons about, for reason strings. */
    private val LABEL_NAMES: Map<Int, String> = mapOf(
        0 to "Speech", 65 to "Hubbub/speech babble", 125 to "Buzz", 130 to "Rattle",
        132 to "Music", 277 to "Wind", 279 to "Wind noise (microphone)", 294 to "Vehicle",
        300 to "Motor vehicle (road)", 301 to "Car", 306 to "Skidding", 307 to "Tire squeal",
        320 to "Motorcycle", 321 to "Traffic noise", 327 to "Train wheels squealing",
        337 to "Engine", 338 to "Light engine (high frequency)", 342 to "Medium engine",
        343 to "Heavy engine", 344 to "Engine knocking", 345 to "Engine starting",
        346 to "Idling", 347 to "Accelerating, revving, vroom", 355 to "Squeak",
        392 to "Buzzer", 398 to "Mechanisms", 401 to "Tick", 402 to "Tick-tock",
        403 to "Gears", 469 to "Scrape", 479 to "Squeal", 482 to "Whir", 483 to "Clatter",
        485 to "Clicking", 486 to "Clickety-clack", 490 to "Hum", 494 to "Silence",
        500 to "Inside, small room", 501 to "Inside, large room", 502 to "Inside, public space",
        503 to "Outside, urban", 504 to "Outside, rural", 507 to "Noise",
        508 to "Environmental noise", 509 to "Static", 510 to "Mains hum",
        514 to "White noise", 515 to "Pink noise"
    )

    /**
     * Strongest single observation within a group.
     *
     * @property score      Max member score. Uncalibrated — NOT a probability of the category.
     * @property topIndex   AudioSet index that produced [score], or -1 if the group is empty.
     * @property topLabel   Display name for [topIndex].
     */
    data class GroupEvidence(val score: Float, val topIndex: Int, val topLabel: String) {
        fun describe(): String = if (topIndex < 0) "none" else "$topLabel=${"%.3f".format(score)}"
    }

    /** All group scores for one clip — exposed so debug tooling can show the working. */
    data class EvidenceBreakdown(
        val vehicle: GroupEvidence,
        val engine: GroupEvidence,
        val friction: GroupEvidence,
        val rattle: GroupEvidence,
        val mechanical: GroupEvidence,
        val electrical: GroupEvidence,
        val ambient: GroupEvidence,
        val humanMusic: GroupEvidence
    ) {
        fun lines(): List<String> = listOf(
            "vehicle     ${vehicle.describe()}",
            "engine      ${engine.describe()}",
            "friction    ${friction.describe()}",
            "rattle      ${rattle.describe()}",
            "mechanical  ${mechanical.describe()}",
            "electrical  ${electrical.describe()}",
            "ambient     ${ambient.describe()}",
            "human/music ${humanMusic.describe()}"
        )
    }

    /** Computes every group's strongest observation. Pure — no decision logic. */
    fun breakdown(meanScores: FloatArray): EvidenceBreakdown = EvidenceBreakdown(
        vehicle    = groupMax(meanScores, VEHICLE_INDICES),
        engine     = groupMax(meanScores, ENGINE_INDICES),
        friction   = groupMax(meanScores, FRICTION_INDICES),
        rattle     = groupMax(meanScores, RATTLE_INDICES),
        mechanical = groupMax(meanScores, MECHANICAL_INDICES),
        electrical = groupMax(meanScores, ELECTRICAL_INDICES),
        ambient    = groupMax(meanScores, AMBIENT_INDICES),
        humanMusic = groupMax(meanScores, HUMAN_MUSIC_INDICES)
    )

    /**
     * Maps mean YAMNet scores to a RoadSide evidence category.
     *
     * @param meanScores Element-wise mean of scores[521] across all windows.
     */
    fun translate(meanScores: FloatArray): AudioClassificationResult {
        if (meanScores.size < YamNetInterpreter.NUM_CLASSES) {
            Log.w(TAG, "Unexpected score vector size: ${meanScores.size}")
            return unknownResult("score vector was ${meanScores.size} long, expected ${YamNetInterpreter.NUM_CLASSES}")
        }

        val b = breakdown(meanScores)
        Log.d(TAG, "Evidence breakdown: ${b.lines().joinToString(" | ")}")

        val vehicleContext = b.vehicle.score >= T_PRESENCE || b.engine.score >= T_PRESENCE

        return when {
            // ── Brake-like friction ──────────────────────────────────────────────
            // Must out-score general mechanical noise, otherwise a rattly clip with a
            // little high-frequency content would read as a brake.
            b.friction.score >= T_FRICTION && b.friction.score >= b.mechanical.score ->
                result(
                    label = LABEL_BRAKE_SQUEAL,
                    score = b.friction.score,
                    description = "High-frequency friction sound detected",
                    reason = "friction ${b.friction.describe()} >= $T_FRICTION and >= mechanical ${b.mechanical.describe()}",
                    breakdown = b
                )

            // ── Electrical / relay clicking ──────────────────────────────────────
            // Only when the engine is NOT the dominant sound — a running engine rules
            // out the flat-battery interpretation this category exists for.
            b.electrical.score >= T_ELECTRICAL &&
                b.electrical.score > b.engine.score &&
                b.electrical.score > b.friction.score ->
                result(
                    label = LABEL_CLICKING_ELEC,
                    score = b.electrical.score,
                    description = "Clicking or buzzing sound detected",
                    reason = "electrical ${b.electrical.describe()} >= $T_ELECTRICAL, above engine ${b.engine.describe()}",
                    breakdown = b
                )

            // ── Chain-like evidence — deliberately hard to reach ──────────────────
            // Requires a rattle-family class to be BOTH above its own threshold AND
            // louder than any engine class. A normally running motorcycle produces high
            // engine scores and low rattle scores, so it cannot satisfy this and falls
            // through to engine_noise below. This is the false-positive path that the
            // previous mapping had wide open.
            //
            // Even when it fires this is weak evidence: AudioSet has no chain class, so
            // "Rattle near a vehicle" is the most that can honestly be claimed.
            b.rattle.score >= T_CHAIN && b.rattle.score > b.engine.score && vehicleContext ->
                result(
                    label = LABEL_CHAIN_NOISE,
                    score = b.rattle.score,
                    description = "Cyclic rattling detected alongside vehicle sounds",
                    reason = "rattle ${b.rattle.describe()} >= $T_CHAIN and above engine ${b.engine.describe()}, " +
                        "vehicle context present (${b.vehicle.describe()})",
                    breakdown = b
                )

            // ── Normal running engine ────────────────────────────────────────────
            // Where an ordinary motorcycle recording is expected to land.
            b.engine.score >= T_PRESENCE ->
                result(
                    label = LABEL_ENGINE_NOISE,
                    score = b.engine.score,
                    description = "Engine or motor sound detected",
                    reason = "engine ${b.engine.describe()} >= $T_PRESENCE, no dominant rattle/friction evidence",
                    breakdown = b
                )

            // ── Mechanical noise without a clear engine ──────────────────────────
            b.mechanical.score >= T_MECHANICAL ->
                result(
                    label = LABEL_MECHANICAL_NOISE,
                    score = b.mechanical.score,
                    description = "General mechanical sound detected",
                    reason = "mechanical ${b.mechanical.describe()} >= $T_MECHANICAL, engine below $T_PRESENCE",
                    breakdown = b
                )

            // ── Vehicle audible but nothing specific ─────────────────────────────
            b.vehicle.score >= T_PRESENCE ->
                result(
                    label = LABEL_ENGINE_NOISE,
                    score = b.vehicle.score,
                    description = "Vehicle sound detected",
                    reason = "vehicle ${b.vehicle.describe()} >= $T_PRESENCE with no specific mechanical evidence",
                    breakdown = b
                )

            // ── Background only ──────────────────────────────────────────────────
            // Reachable: max-aggregation means a single strong Silence/Wind/Noise/Speech
            // observation is enough, instead of the old unreachable 0.30 sum-of-five.
            maxOf(b.ambient.score, b.humanMusic.score) >= T_AMBIENT -> {
                val strongest = if (b.ambient.score >= b.humanMusic.score) b.ambient else b.humanMusic
                result(
                    label = LABEL_AMBIENT_ONLY,
                    score = strongest.score,
                    description = "Background sound only — no vehicle sounds detected",
                    reason = "background ${strongest.describe()} >= $T_AMBIENT, no vehicle or mechanical evidence",
                    breakdown = b
                )
            }

            else -> unknownResult(
                "no group reached its threshold (" + b.lines().joinToString("; ") + ")",
                b
            )
        }
    }

    /** Max member score in [indices], with the index that produced it. */
    private fun groupMax(scores: FloatArray, indices: IntArray): GroupEvidence {
        var bestIdx = -1
        var best = 0f
        for (idx in indices) {
            // Guard against a class map / model mismatch rather than silently scoring 0.
            if (idx >= scores.size) {
                Log.w(TAG, "Index $idx out of range for ${scores.size}-class output — skipped")
                continue
            }
            if (bestIdx == -1 || scores[idx] > best) {
                best = scores[idx]
                bestIdx = idx
            }
        }
        return GroupEvidence(best, bestIdx, LABEL_NAMES[bestIdx] ?: "class_$bestIdx")
    }

    private fun result(
        label: String,
        score: Float,
        description: String,
        reason: String,
        breakdown: EvidenceBreakdown
    ) = AudioClassificationResult(
        label = label,
        evidenceScore = score.coerceIn(0f, 1f),
        labelDescription = description,
        reason = reason,
        topContributor = strongestOverall(breakdown)
    )

    private fun strongestOverall(b: EvidenceBreakdown): String =
        listOf(b.vehicle, b.engine, b.friction, b.rattle, b.mechanical, b.electrical, b.ambient, b.humanMusic)
            .maxByOrNull { it.score }
            ?.describe() ?: "none"

    private fun unknownResult(reason: String, breakdown: EvidenceBreakdown? = null) = AudioClassificationResult(
        label = LABEL_UNKNOWN,
        evidenceScore = 0f,
        labelDescription = "Audio pattern inconclusive — could not identify a vehicle-related sound",
        reason = reason,
        topContributor = breakdown?.let { strongestOverall(it) } ?: "none"
    )
}
